name: 🐞 Bug Report
description: Create a report to help us improve.
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I'm using the latest releases.
          required: true
        - label: Yes, I've searched similar issues on GitHub and didn't find any.
          required: true
        - label: Yes, I've included all information below (version, config, etc).
          required: true

  - type: dropdown
    id: goos
    attributes:
      label: OS?
      options:
        - aix
        - android
        - darwin
        - dragonfly
        - freebsd
        - illumos
        - ios
        - js
        - linux
        - netbsd
        - openbsd
        - plan9
        - solaris
        - wasip1
        - windows
    validations:
      required: true

  - type: dropdown
    id: goarch
    attributes:
      label: Arch?
      options:
        - 'ppc64'
        - '386'
        - 'amd64'
        - 'arm'
        - 'arm64'
        - 'riscv64'
        - 'wasm'
        - 'loong64'
        - 'mips'
        - 'mips64'
        - 'mips64le'
        - 'mipsle'
        - 'ppc64le'
        - s390x
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
      placeholder: Description.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: What did you see instead?
      placeholder: Description.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      render: console
      placeholder: |-
        ```go
        // Paste you code here.
        ```
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version of flock
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: console
      value: |-
        <details>

        ```console
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Go environment (if applicable)
      value: |-
        <details>

        ```console
        $ go version && go env
        # paste output here
        ```

        </details>
    validations:
      required: false
