name: Linting

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  golangci-lint:
    name: Linting
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GO_VERSION: stable
      GOLANGCI_LINT_VERSION: v2.11
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ matrix.os == 'windows-latest' }} # https://github.com/actions/checkout/issues/135
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf input
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  check-github-action:
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          advanced-security: false
          annotations: true
