name: PR only

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:

  pr:
    name: Linting
    strategy:
      matrix:
        go-version: [ stable, oldstable ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GO_VERSION: stable
      GOLANGCI_LINT_VERSION: v1.59
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
